### PR TITLE
[9.99.x-prod][OSL-1.32.2] [Fix apache/incubator-kie-issues#987] Add onError listener

### PR DESCRIPTION
**Pull request by fjtirado**
Merge with https://github.com/kiegroup/kogito-runtimes/pull/30 and https://github.com/kiegroup/kogito-apps/pull/17

Required to cherry-pick https://github.com/apache/incubator-kie-drools/pull/5766 for OSL 1.32.2

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Comment by rgdoliveira** [comment]
I'm working on fixing CI checks for Drools 9.99.x-prod branch. As we didn't have any PRs before for this branch I probably missed to fix them.

**Comment by rgdoliveira** [comment]
@fjtirado PR fixing CI https://github.com/kiegroup/drools/pull/41 is merged, can you please rebase your PR?

**Comment by gmunozfe** [comment]
> Merge with [kiegroup/kogito-runtimes#30](https://github.com/kiegroup/kogito-runtimes/pull/30) and [kiegroup/kogito-apps#17](https://github.com/kiegroup/kogito-apps/pull/17)
> 
> Required to cherry-pick [apache/incubator-kie-issues#987](https://github.com/apache/incubator-kie-issues/issues/987) for OSL 1.32.2

@fjtirado You meant cherry-picked from https://github.com/apache/incubator-kie-drools/pull/5766

**Review by gmunozfe — APPROVED** [review]
LGTM, let's wait the CI to be green, thanks a lot @fjtirado !

**Review by rgdoliveira — APPROVED** [review]

**Pull request merged**
