### PR TITLE
simplified if statement

### PR DESCRIPTION
**Pull request by talhacevik**

### CODE REVIEW

**Comment by talhacevik** [comment]
> Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

ok

**Comment by triceo** [comment]
ok to test

**Review by triceo — APPROVED** [review]

**Comment by triceo** [comment]
Thanks for the contribution!

**Comment by triceo** [comment]
FYI we did have to revert this change. The construct was apparently designed to test ternary expressions in just the way it was written.

**Pull request merged**
