### PR TITLE
[RHDM-2029] Executable model doesn't report an error when duplicated

### PR DESCRIPTION
**Pull request by tkobayas**
- Additional tests and fix

**Ports**

This PR is for 7.x

**JIRA**: 

* https://issues.redhat.com/browse/RHDM-2029

This is an additional  tests and fix to https://github.com/kiegroup/drools/pull/59

### CODE REVIEW

**Comment by tkobayas** [comment]
jenkins pr: not related to this PR

```
[2024-07-02T07:30:48.281Z] [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar (default) on project drools-retediagram: Could not find the pullrequest with key '61': Error 404 on https://sonarcloud.io/api/alm_integration/show_pullrequest?project=org.drools%3Adrools&pullrequestKey=61 : {"errors":[{"msg":"The pullrequest could not be found"}]} -> [Help 1]
```

jenkins cdb: not related to this PR
```
[2024-07-02T07:06:24.376Z] Caused by: java.io.FileNotFoundException: /home/jenkins/workspace/KIE/7.x/compile/drools-7.x.compile/bc/kiegroup_droolsjbpm-integration/kie-server-parent/kie-server-services/kie-server-services-prometheus/target/classes (Is a directory)
```

**Comment by tkobayas** [comment]
https://github.com/kiegroup/drools/pull/59 had a defect. It worked well when the included kbase is a separated kjar. But it threw NPE when one kjar contains both the included kbase and the main kbase.

This PR is additional test and fix PR to cover the scenario.

**Comment by tkobayas** [comment]
@mariofusco @lucamolteni @pibizza Please review, thanks!

**Review by lucamolteni — APPROVED** [review]

**Review by pibizza — APPROVED** [review]
LGTM

**Pull request merged**
