### PR TITLE
[7.67.x-blue] Fix ActionFieldValue clone (#5991)

### PR DESCRIPTION
**Pull request by yesamer**
Backport of https://github.com/apache/incubator-kie-drools/pull/5991 in `kiegroup` repo

* [private-bamoe-issues#2091] Fix ActionFieldValue clone

* Fix template test

* [private-bamoe-issues#2091] Fix ActionFieldValue clone

### CODE REVIEW

**Comment by yesamer** [comment]
Jenkins run fdb

**Review by gitgabrio — APPROVED** [review]
Thx @yesamer

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins retest this

**Review by mariofusco — APPROVED** [review]

**Comment by yesamer** [comment]
Jenkins retest this

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins retest this

**Comment by yesamer** [comment]
Jenkins retest this

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins retest this

**Comment by yesamer** [comment]
Jenkins run cdb

**Comment by yesamer** [comment]
Jenkins retest this

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins retest this

**Comment by yesamer** [comment]
Jenkins retest this

**Comment by yesamer** [comment]
Jenkins retest this

**Comment by yesamer** [comment]
@mareknovotny I did my best to be a good citizen here, but I have the impression those PR builds will never be green. Do you mind taking a look, please?

//cc @porcelli

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
@yesamer well, if you check the Jenkins build log it shows you that error is in the followed sonar analysis 

```
[2024-07-11T07:38:59.738Z] [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar (default) on project drools-retediagram: Could not find the pullrequest with key '65': Error 404 on https://sonarcloud.io/api/alm_integration/show_pullrequest?project=org.drools%3Adrools&pullrequestKey=65 : {"errors":[{"msg":"The pullrequest could not be found"}]} -> [Help 1]
```

it was already reported this branch has problems with configured sonarcloud.io projects.

**Comment by gitgabrio** [comment]
@mareknovotny OOC: where is that maven plugin should get the `projectKey` to be used in the rest invocation ?
IIUC, the endpoint should be 
https://sonarcloud.io/api/alm_integration/show_pullrequest?project=kiegroup_drools&pullrequestKey=65

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
> @mareknovotny OOC: where is that maven plugin should get the `projectKey` to be used in the rest invocation ? IIUC, the endpoint should be https://sonarcloud.io/api/alm_integration/show_pullrequest?project=kiegroup_drools&pullrequestKey=65

there is no property right now as using the default, but you can set it up for this case if required see https://stackoverflow.com/questions/23312738/override-sonar-projectkey-when-using-maven

**Comment by gitgabrio** [comment]
Jenkins retest this

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Pull request merged**
